### ISSUE TITLE
Adding Text Instead of Images

### ISSUE THREAD

**Issue by TosinAF** [rnystrom/RNFrostedSidebar#1]
Basically, I needed to add Text Instead of Images to RNFrostedSidebar. I was curious to see if you'd want me to make a pull request to add this feature to RNFrostedSidebar. I had to pull out the implementation of RNCalloutItemView into a separate file in order to make an abstract class & which the process by which u add images & that by which u add text inherit from. This was to reduce me repeating code.

Let me know if you'd like me to do this.

**Comment by rnystrom** [comment]
Do you have a fork where this is implemented? I'd like to check it out. I really don't like the idea of pulling out the callout item class because I like this to be as abstracted from the user as possible. Providing them a subclass gives more possibility for error.

I toyed around with this idea but decided to ignore it because I didn't want to muck up the design. If it's done tastefully I'm very interested.

**Comment by ikoller47** [comment]
I would be interested in seeing the pull request as I want to use text instead of images as well.

**Comment by TosinAF** [comment]
working on it, should have one up in a few hours, sorry for the delay

**Comment by adrian-schnell** [comment]
do you have anything ready to use @TosinAF? I'd love to use text instead of images as well.
