### ISSUE TITLE
IOS 7 SideBar

### ISSUE THREAD

**Issue by InquirerMegamobileInc** [rnystrom/RNFrostedSidebar#11]
when I was using IOS 6.1.3 the RNFrostedsidebar is still working but when i upgraded to IOS 7 the RNFrostedSidebar doesn't work anymore what should i do to make the RNFrostedSidebar work again?

**Comment by ashishfission** [comment]
same issue with me....side bar is coming but there is no images or button....help ..
xcode 4
iphone 4s iOS 7.02

**Comment by rnystrom** [comment]
Xcode 4, and iOS 7? I'm confused.Can you provide more details on what is happening?

**Comment by InquirerMegamobileInc** [comment]
on ios 7 the sidebar buttons/ images dissapear, this is the screenshot http://imgur.com/FYrlNCU.

**Comment by ashishfission** [comment]
@ChineseGirl24 : ah ha got it...was facing same issue...this issue is occurring because you may be using iOS6 sdk inplace of iOS 7... SpringAnimation is available from iOS 7 ..

there is one minor modification...

search for  
if (sdkHasSpringAnimation) {

```
        [self animateSpringWithView:view idx:idx initDelay:initDelay];
    }
    else {
        [self animateFauxBounceWithView:view idx:idx initDelay:initDelay];
    }
```

replace with ----

if (sdkHasSpringAnimation) {
            //use below code in xcode 5
            //[self animateSpringWithView:view idx:idx initDelay:initDelay];
            [self animateFauxBounceWithView:view idx:idx initDelay:initDelay];

```
    }
    else {
        [self animateFauxBounceWithView:view idx:idx initDelay:initDelay];
    }
```

hope it works....any help  skype id  --- ashishcse    

@rnystrom  you are rocking ....

**Comment by InquirerMegamobileInc** [comment]
@rnystrom you rock :) thanks
@ashishfission  thanks :) you also rock :))

**Comment by rnystrom** [comment]
Ahhhhh, I see what's happening. Great find @ashishfission!

I'm trying to decide if I should try to fix this or not. Definitely an edge-case. Happy coding @ChineseGirl24 :)
