### ISSUE TITLE
Any plans to add labels to the buttons? 

### ISSUE THREAD

**Issue by appdicted** [rnystrom/RNFrostedSidebar#13]

**Comment by rnystrom** [comment]
I'm really hard-pressed to ever add this because
1. It breaks the purpose of the tool and pop animations with text wont be very tasteful.
2. I have no designs to implement this off of. The original was taken from Dribbble and I'd like to keep it as true to the original work as possible.

I'd entertain the idea if someone were to show me a compelling Pull Request, but I have no motivation to add this currently.
